services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: poetry run python app.py
    ports:
      - "7860:7860"
    volumes:
      - .:/app
    depends_on:
      - qdrant

  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
